name: Build and Deploy VitePress Site

on:
  push:
    branches:
      - main  # Assuming your primary branch is named main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'  # Choose the Node.js version that matches your development environment

    - name: Install dependencies
      run: npm install

    - name: Build VitePress site
      run: npm run docs:build

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22  # Or any custom port if your SSH server uses one
        source: "dist/*"
        target: "/var/www/vitepress/"
        rm: true  # Remove the files at the target before copying

    - name: Execute remote commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/vitepress/
          # Any command you need to execute, for example to restart a service
          # sudo systemctl restart nginx
